variables:
  # Namespaces Kubernetes
  KUBE_NAMESPACE_DEV: dev
  KUBE_NAMESPACE_QA: qa
  KUBE_NAMESPACE_STAGING: staging
  KUBE_NAMESPACE_PROD: prod

  # IPs des environnements
  IP_DEV: 80.124.62.186
  IP_QA: 80.124.62.187
  IP_STAGING: 80.124.62.186
  IP_PROD: 80.124.62.186

  # NodePorts exposés pour chaque environnement
  NODEPORT_DEV: 30000
  NODEPORT_QA: 30003
  NODEPORT_STAGING: 30001
  NODEPORT_PROD: 30002

  # Image Docker sur DockerHub
  IMAGE_NAME: salioudiedhiou/gitlab-fastapi

stages:
  - test
  - build
  - run
  - push
  - deploy_dev
  - deploy_qa
  - deploy_staging
  - deploy_prod

test:
  stage: test
  image: python:3.12
  tags:
    - gitlab
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install fastapi pytest httpx jinja2
    - export PYTHONPATH="$PYTHONPATH:$(pwd)"
    - pytest app/test_main.py

build:
  stage: build
  tags:
    - gitlab
  script:
    - docker info
    - docker build -t "$IMAGE_NAME:latest" .
    - docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"

run:
  stage: run
  tags:
    - gitlab
  before_script:
    - which curl || apk add --no-cache curl
  script:
    - docker rm -f fastapi || true
    - docker run -d -p 80:80 --name fastapi "$IMAGE_NAME:latest"
    - sleep 10
    - curl --fail --max-time 10 http://localhost || (echo "L'application ne répond pas" && docker logs fastapi && exit 1)
    - docker stop fastapi
    - docker rm fastapi

push:
  stage: push
  tags:
    - gitlab
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - docker push "$IMAGE_NAME:latest"

stop_dev:
  stage: deploy_dev
  tags:
    - gitlab
  variables:
    NAMESPACE: $KUBE_NAMESPACE_DEV
  when: manual
  environment:
    name: dev-$CI_COMMIT_REF_NAME
    action: stop
  image: alpine/helm:3.11.2
  script:
    - helm uninstall app -n "$NAMESPACE" || echo "Release not found"

stop_qa:
  stage: deploy_qa
  tags:
    - gitlab
  variables:
    NAMESPACE: $KUBE_NAMESPACE_QA
  when: manual
  environment:
    name: qa-$CI_COMMIT_REF_NAME
    action: stop
  image: alpine/helm:3.11.2
  script:
    - helm uninstall app -n "$NAMESPACE" || echo "Release not found"

stop_staging:
  stage: deploy_staging
  tags:
    - gitlab
  variables:
    NAMESPACE: $KUBE_NAMESPACE_STAGING
  when: manual
  environment:
    name: staging-$CI_COMMIT_REF_NAME
    action: stop
  image: alpine/helm:3.11.2
  script:
    - helm uninstall app -n "$NAMESPACE" || echo "Release not found"

.deploy_template: &deploy_template
  image: alpine/helm:3.11.2
  tags:
    - gitlab
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG_B64" | base64 -d > ~/.kube/config
    - export KUBECTL_OPTIONS="--insecure-skip-tls-verify=true"
    - kubectl get nodes $KUBECTL_OPTIONS
  script:
    - cp fastapi/values.yaml values.yml
    - >
      helm upgrade --install app fastapi/ --values=values.yml
      --namespace "$NAMESPACE"
      --set image.repository="$IMAGE_NAME"
      --set image.tag="$CI_COMMIT_SHORT_SHA"
      --set service.nodeport="$NODEPORT"
      --insecure-skip-tls-verify

deploy_dev:
  <<: *deploy_template
  stage: deploy_dev
  environment:
    name: dev-$CI_COMMIT_REF_NAME
    url: http://$IP_DEV:$NODEPORT_DEV
    on_stop: stop_dev
  variables:
    NAMESPACE: $KUBE_NAMESPACE_DEV
    NODEPORT: $NODEPORT_DEV

deploy_qa:
  <<: *deploy_template
  stage: deploy_qa
  environment:
    name: qa-$CI_COMMIT_REF_NAME
    url: http://$IP_QA:$NODEPORT_QA
    on_stop: stop_qa
  variables:
    NAMESPACE: $KUBE_NAMESPACE_QA
    NODEPORT: $NODEPORT_QA

deploy_staging:
  <<: *deploy_template
  stage: deploy_staging
  environment:
    name: staging-$CI_COMMIT_REF_NAME
    url: http://$IP_STAGING:$NODEPORT_STAGING
    on_stop: stop_staging
  variables:
    NAMESPACE: $KUBE_NAMESPACE_STAGING
    NODEPORT: $NODEPORT_STAGING

deploy_prod:
  <<: *deploy_template
  stage: deploy_prod
  when: manual
  only:
    - main
  environment:
    name: prod
    url: http://$IP_PROD:$NODEPORT_PROD
  variables:
    NAMESPACE: $KUBE_NAMESPACE_PROD
    NODEPORT: $NODEPORT_PROD
